/**
 * Exporting a note to a standalone HTML file reuses `printNote.ts`'s own
 * document/stylesheet builder (Phase 1 of this ROADMAP item) rather than
 * a second Markdown-to-HTML pipeline: this module's only real job is
 * making the already-rendered Preview pane's local images portable.
 *
 * The Preview pane's own images already resolved to the app's internal
 * `asset://`-style URL (`workspace/tauriBridge.ts`'s `fileSrc`), loadable
 * only from inside this running app. A standalone `.html` file opened
 * later, on another machine, with no Leotheca running, needs the actual
 * image bytes embedded as `data:` URIs instead.
 */

import { buildPrintDocument } from "./printNote";

async function responseToDataUrl(response: Response): Promise<string> {
  const blob = await response.blob();
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(reader.error ?? new Error("Could not read image data"));
    reader.readAsDataURL(blob);
  });
}

export interface InlineLocalImagesDeps {
  /** Overridable for tests; defaults to the global `fetch`. A real
   * caller never needs to override this: `fetch()` against the Preview
   * pane's own already-resolved image URLs works from inside the running
   * app the same way loading them as `<img src>` already does (that's
   * the same protocol handler, just invoked through a different API). */
  fetchImpl?: typeof fetch;
  /** Overridable for tests; defaults to a real `DOMParser`. */
  parser?: DOMParser;
}

/**
 * Replaces every `<img>` in `html` whose `src` is not already a `data:`
 * URI with one, fetching the real bytes first. An image that fails to
 * fetch (a broken attachment, an already-unresolved placeholder) is left
 * with its original `src` rather than failing the whole export: it just
 * won't display when the exported file is opened standalone, the same
 * way a broken image behaves anywhere else.
 */
export async function inlineLocalImages(html: string, deps: InlineLocalImagesDeps = {}): Promise<string> {
  const { fetchImpl = fetch, parser = new DOMParser() } = deps;

  // Parse the fragment ONLY to enumerate which `<img src>` values exist and
  // need inlining. Do NOT return `parsed.body.innerHTML`: that re-serializes
  // the whole fragment through the HTML parser, which silently restructures
  // any "imperfect" HTML the Preview pane produces (e.g. injects a `<tbody>`
  // into a `<table>`, closes an early `<p>` before a nested `<div>`, repairs
  // an unclosed tag). That is a faithful-parse but unfaithful-output bug for
  // an export function that must preserve the note's content exactly. Instead
  // we keep the original string and substitute only the `<img src>` values.
  const parsed = parser.parseFromString(html, "text/html");
  const imageSources = Array.from(
    new Set(
      Array.from(parsed.querySelectorAll("img"))
        .map((img) => img.getAttribute("src"))
        .filter((src): src is string => !!src && !src.startsWith("data:")),
    ),
  );

  const dataUriBySrc = new Map<string, string>();
  await Promise.all(
    imageSources.map(async (src) => {
      try {
        const response = await fetchImpl(src);
        if (!response.ok) return;
        dataUriBySrc.set(src, await responseToDataUrl(response));
      } catch {
        // Leave the original src: one unreachable attachment shouldn't
        // fail the whole export.
      }
    }),
  );

  if (dataUriBySrc.size === 0) return html;

  // Replace only the `src="..."` value inside each `<img ...>` tag, leaving
  // the rest of the fragment byte-for-byte untouched.
  //
  // Real attribute values generated by the Preview pane are always quoted, so
  // we match `src=` immediately followed by a quote (double or single) and
  // capture that quoted value. This intentionally does NOT match a bare
  // `src=` followed by an unquoted token, which is how the substring `src=`
  // inside another attribute's *value* (e.g. alt="use src= for details") would
  // otherwise be mistaken for the image source.
  //
  // `[^>]*` for the tag body is deliberate: an attribute *value* may legally
  // contain `>` (e.g. alt="a > b"), and `[^>]*` keeps scanning inside that
  // value so the real `src=` later in the tag is still found. The only HTML
  // the Preview pane can produce where a bare `>` inside a value would cut
  // the tag short is malformed markup that never renders in the pane either.
  const SRC_ATTR = /src\s*=\s*("([^"]*)"|'([^']*)')/gi;
  return html.replace(/<img\b[^>]*>/gi, (tag) => {
    // Find the LAST `src=` in the tag: a genuine `src` attribute always wins
    // over the substring `src=` inside an earlier attribute's *value* (e.g.
    // alt="use src= for details"), and a duplicate `src` attribute never
    // exists in HTML produced by the Preview pane (it comes from a single
    // well-formed `<img>` element's serialization).
    let srcMatch: RegExpExecArray | null = null;
    SRC_ATTR.lastIndex = 0;
    let candidate: RegExpExecArray | null;
    while ((candidate = SRC_ATTR.exec(tag)) !== null) srcMatch = candidate;
    if (!srcMatch) return tag;
    const quote = srcMatch[1].startsWith("'") ? "'" : '"';
    const original = srcMatch[2] ?? srcMatch[3] ?? "";
    if (!original || original.startsWith("data:")) return tag; // already inlined
    const replacement = dataUriBySrc.get(original);
    if (!replacement) return tag; // fetch failed: keep byte-for-byte
    const valueWithQuotes = srcMatch[1];
    // srcMatch.index points at the 's' in `src`; srcMatch[0] is the whole
    // `src\s*=\s*"..."` match and BEGINS at that same index, so the quoted
    // value's absolute position in the tag is exactly srcMatch.index + the
    // length of everything before the value inside srcMatch[0] (the
    // `src`, `=`, and any whitespace). Computing that offset as
    // `srcMatch[0].length - valueWithQuotes.length` works for both quote
    // styles and is immune to the value (or any prefix of it) appearing
    // earlier inside another attribute's value, which is exactly the
    // class of bug `String.prototype.replace`'s from-position-0 search
    // would suffer.
    const valueOffset = (srcMatch.index as number) + (srcMatch[0].length - valueWithQuotes.length);
    return (
      tag.slice(0, valueOffset) +
      `${quote}${replacement}${quote}` +
      tag.slice(valueOffset + valueWithQuotes.length)
    );
  });
}

/** Builds the final standalone document for `bodyHtml` (Preview output
 * whose local images `inlineLocalImages` has already inlined). Delegates
 * to `printNote.ts`'s `buildPrintDocument`: the same document this app
 * builds to print a note is also a perfectly good standalone export --
 * opening the exported file and using the browser's own print function
 * still works, not just viewing it. */
export function buildExportDocument(title: string, bodyHtml: string): string {
  return buildPrintDocument(title, bodyHtml);
}
